task_name: atac_cross_finetune_100bins_multi_tissue_chr_and_batch

train:
  # for ditributed training
  local_rank: 0
  # random seed
  seed: 2002

  # training hyperparameters
  batch_size: 16
  lr: 1e-4
  epochs: 50
  gradient_accumulation_steps: 20
  amp: True
  save_ckpt_freq: 20
  resume: False

  model:
    encoder: transformer
    pretrained: /home/jwu418/workspace/scMultiomics/experiment/atac_cross_pretrain_multi_tissue_chr_and_batch/ckpts/Epoch_140_Step_202580_atac_cross_pretrain_multi_tissue_chr_and_batch.pth # set to None if not using pretrained model
    embedding_method: id_only
    atac_max_len: 8000
    rna_max_len: 8000
    embedding_dim: 512
    num_layers: 6
    head_num: 8
    head_dim: 1024
    dropout: 0.2
    additional_config_path: /path/to/additional_config.json
    cell_emb_style: cls
    mvc_arch_style: concat query
    use_batch_labels: True
    use_chr_labels: True
  
  task_weight:
    cell_type: 0.0
    mvc: 1.0

valid:
  freq: 2

data:
  bin_num: &bn 2 # bin number in pretrained data
  append_cls: True
  train:
    atac_path: /home/jwu418/workspace/data/ours/test/bmmc_kidney_paired_atac.h5ad
    atac_key: X
    rna_path: /home/jwu418/workspace/data/ours/test/bmmc_kidney_rna_binned_binning_100.h5ad
    rna_key: X_binned
  test:
    atac_path: /home/jwu418/workspace/data/ours/valid/bmmc_kidney_paired_atac.h5ad
    atac_key: X
    rna_path: /home/jwu418/workspace/data/ours/valid/bmmc_kidney_rna_binned_binning_100.h5ad
    rna_key: X_binned

vocab:
  rna_path: /home/jwu418/workspace/data/ours/vocab/bmmc_rna_vocab.json
  atac_path: /home/jwu418/workspace/data/ours/vocab/bmmc_atac_vocab.json
  cell_type_path: /home/jwu418/workspace/data/ours/vocab/bmmc_kidney_cell_vocab.json
  batch_path: /home/jwu418/workspace/data/ours/vocab/bmmc_kidney_batch_vocab.json
  chr_path: /home/jwu418/workspace/data/ours/vocab/chr_vocab.json
  gene2chr_path: /home/jwu418/workspace/data/ours/vocab/gene2chr.json
  special_tokens:
    pad: {token: <pad>, value: 100}
    # value of the mask is 1 plus bin_num
    mask: {token: <mask>, value: 101}
    cls: {token: <cls>, value: 0}

