task_name: bmmc_atlas_zero_inflated_finetune

train:
  seed: 2002
  batch_size: 2
  lr: 1e-4
  epochs: 100
  gradient_accumulation_steps: 180
  amp: True
  save_ckpt_freq: 20
  resume: False

  model:
    encoder: transformer
    pretrained: /home/jwu418/workspace/scMultiomics/experiment/mini_atlas_pretrain/ckpts/pretrain.pth
    embedding_method: id_only
    atac_max_len: 12000
    rna_max_len: 2000
    embedding_dim: 512
    num_layers: 6
    head_num: 8
    head_dim: 1024
    dropout: 0.15
    cell_emb_style: cls
    mvc_arch_style: gene-specific concat query
    use_batch_labels: False
    use_chr_labels: True
    gene_specific_fp16: False
    # New parameters for zero-inflated model
    use_zero_inflated: True
    regression_max_value: 9.0
    zero_threshold: 0.6  # For inference (used in eval)
  
  task_weight:
    cell_type: 1.0
    mvc: 1.0  # Overall weight for value_loss (set to 0 to disable if needed)
    zero_bce: 1.0  # Weight for BCE component within value_loss
    value_mse: 0.05  # Weight for MSE component within value_loss

valid:
  freq: 2

data:
  bin_num: 2
  append_cls: True
  train:
    atac_path: /home/jwu418/workspace/data/ours/train/bmmc_atlas_atac.h5ad
    atac_key: X
    rna_path: /home/jwu418/workspace/data/ours/train/bmmc_atlas_rna_binning_10.h5ad
    rna_key: X
  test:
    atac_path: /home/jwu418/workspace/data/ours/valid/bmmc_atlas_atac.h5ad
    atac_key: X
    rna_path: /home/jwu418/workspace/data/ours/valid/bmmc_atlas_rna_binning_10.h5ad
    rna_key: X

vocab:
  rna_path: /home/jwu418/workspace/data/ours/vocab/rna_vocab.json
  atac_path: /home/jwu418/workspace/data/ours/vocab/atac_vocab.json
  cell_type_path: /home/jwu418/workspace/data/ours/vocab/fine_tune_cell_type_vocab.json
  batch_path: /home/jwu418/workspace/data/ours/vocab/fine_tune_batch_vocab.json
  chr_path: /home/jwu418/workspace/data/ours/vocab/chr_vocab.json
  gene2chr_path: /home/jwu418/workspace/data/ours/vocab/gene2chr.json
  hvg_path: /home/jwu418/workspace/data/ours/variable_genes/bmmc_atlas_variable_genes.csv
  special_tokens:
    pad: {token: <pad>, value: 10}
    mask: {token: <mask>, value: 11}
    cls: {token: <cls>, value: 0}
